rplidar_ros2_driver_node:
  ros__parameters:
    port: /dev/ttyLiDAR
    frame_id: base_scan
    ignore_array: ""
    baudrate: 128000
    lidar_type: 1
    device_type: 0
    sample_rate: 5 #9
    abnormal_check_count: 4
    resolution_fixed: true
    reversion: true
    inverted: true
    auto_reconnect: true
    isSingleChannel: false
    intensity: false
    support_motor_dtr: true
    angle_max: 180.0
    angle_min: -180.0
    range_max: 12.0 #64.0
    range_min: 0.1 #0.01
    frequency: 10.0
    invalid_range_is_inf: false
